AllCops:
  Exclude:
    - 'lib/foodcritic/rules/etsy.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 15

HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - Rakefile
    - Berksfile
    - Gemfile
    - Policyfile.rb
